# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MTSW
url: "https://marcustohsw.github.io"
baseurl: ""
email:
description: >- # this means to ignore newlines until "baseurl:"
  Marcus Toh's personal portfolio website.
linkedin_username: marcustohsw
github_username: marcustohsw
huggingface_username: marcustoh
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
timezone: Asia/Singapore

include:
  - _pages

collections:
  projects:
    output: true
    permalink: /projects/:path/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Marcus Toh"
  avatar : "/assets/images/IMG_7679.jpg"
  bio    : "AI & Cybersecurity Student"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/marcustohsw/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marcustohsw"
    - label: "Hugging Face"
      icon: "fab fa-fw fa-hugging-face"
      url: "https://huggingface.co/marcustoh"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:marcustohsw@icloud.com"

atom_feed:
  hide: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marcustohsw"
    - label: "Hugging Face"
      icon: "fab fa-fw fa-hugging-face"
      url: "https://huggingface.co/marcustoh"

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      author_profile: true
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
